name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Get code #obter o código
      uses: actions/checkout@v4

    - name: Install Node lts/* #instalar node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies #Instalar dependências
      run: npm install

    - name: Install Playwright Browsers #Instalar browsers e bibliotecas adicionais
      run: npx playwright install --with-deps

    - name: Run E2E tests # Execução dos testes
      run: npx playwright test

    - name: Publish HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
